setono_sylius_lagersystem_api_shipment_index:
    path: /shipments
    methods: [GET]
    defaults:
        _controller: setono_sylius_lagersystem.controller.shipment.shipment_index_action

setono_sylius_lagersystem_api_product_variant_index:
    path: /product-variants
    methods: [GET]
    defaults:
        _controller: setono_sylius_lagersystem.controller.product.product_variant_index_action

setono_sylius_lagersystem_api_product_variant_show:
    path: /product-variants/{code}
    methods: [GET]
    defaults:
        _controller: setono_sylius_lagersystem.controller.product.product_variant_show_action
